// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1503:Braces should not be omitted", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Middlewares.ErrorHandlingMiddleware.HandleExceptionAsync(Microsoft.AspNetCore.Http.HttpContext,System.Exception)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1516:Elements should be separated by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.#ctor(Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1201:A constructor should not follow a property", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.#ctor(Microsoft.Extensions.Configuration.IConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter env of method Configure is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1028:Code should not contain trailing whitespace", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1116:The parameters should begin on the line after the declaration, whenever the parameter span across multiple lines", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,UsersApp.WebApi.Configurations.ConnectionConfig)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1110:Opening parenthesis or bracket should be on declaration line.", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.ConfigureDatabase(Microsoft.Extensions.DependencyInjection.IServiceCollection,UsersApp.WebApi.Configurations.ConnectionConfig)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1028:Code should not contain trailing whitespace", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter rules of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Validation.FluentValidationRules.#ctor(FluentValidation.IValidatorFactory,System.Collections.Generic.IEnumerable{MicroElements.Swashbuckle.FluentValidation.FluentValidationRule},Microsoft.Extensions.Logging.ILoggerFactory)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1503:Braces should not be omitted", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Validation.FluentValidationRules.ApplyRulesToSchema(Swashbuckle.AspNetCore.Swagger.Schema,Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext,FluentValidation.IValidator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Validation.FluentValidationRules.CreateDefaultRules~MicroElements.Swashbuckle.FluentValidation.FluentValidationRule[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1009:Closing parenthesis should not be followed by a space.", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Validation.FluentValidationRules.CreateDefaultRules~MicroElements.Swashbuckle.FluentValidation.FluentValidationRule[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1003:Operator '(ILengthValidator)' should not be followed by whitespace.", Justification = "<Pending>", Scope = "member", Target = "~M:UsersApp.WebApi.Validation.FluentValidationRules.CreateDefaultRules~MicroElements.Swashbuckle.FluentValidation.FluentValidationRule[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1052:Type 'Program' is a static holder type but is neither static nor NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:UsersApp.WebApi.Program")]