services:
  users-api:
    container_name: users-example-api
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - ./users-api.env
    depends_on:
      - sqlserver

  sqlserver:
    container_name: users-example-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
    env_file:
      - ./sqlserver.env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: